export const tableFields = [
	'name',
	'company',
	'category',
	'postingDate',
	'status',
	'postingMedia',
	'employmentType',
	'noOfOpenings',
	'minSalary',
	'jobLocationType',
	'jobLocation',
	'shift',
	'isActive',
	'applicationUrl',
];

export const fields = [
	'name',
	'company',
	'status',
	'noOfOpenings',
	'email',
	'category',
	'postingDate',
	'postingMedia',
	'experienceLevel',
	'educationLevel',
	'applicationProcess',
	'shift',
	'phone',
	'website',
	'address',
	'city',
	'country',
	'industry',
	'companyDescription',
	'employmentType',
	'jobLocationType',
	'jobLocation',
	'minSalary',
	'maxSalary',
	'salaryType',
	'salaryCurrency',
	'jobDescription',
	'requirements',
	'qualifications',
	'responsibilities',
	'tags',
	'applicationUrl',
	'companyLogo',
	'skills',
	'benefits',
	'addedBy',
	'isActive',
	'deadline',
	'file',
	'fileUrl',
];

export const formFields = [
	{
		sectionTitle: 'Basic Information',
		fields: [
			'name',
			['company', 'category'],
			['website', 'status'],
			['postingDate', 'deadline'],
			['postingMedia', 'applicationUrl'],
			'tags',
		],
	},
	{
		sectionTitle: 'Job Details',
		fields: [
			['employmentType', 'noOfOpenings'],
			['minSalary', 'maxSalary'],
			['salaryType', 'shift'],
			['jobLocationType', 'jobLocation'],
		],
	},
	{
		sectionTitle: 'Contact & Location',
		fields: [['phone', 'email'], ['city', 'country'], 'address'],
	},
	{
		sectionTitle: 'Company Descroption',
		fields: ['companyDescription'],
	},
	{
		sectionTitle: 'Job Description',
		fields: [
			'jobDescription',
			'responsibilities',
			'requirements',
			'qualifications',
			'benifits',
			'skills',
			'experienceLevel',
			'educationLevel',
		],
	},
	{
		sectionTitle: 'Relevant Files & Documents',
		description: 'Upload Relevant Documents and files for this job post',
		fields: ['file', 'fileUrl'],
	},
];
