export const tableFields = [
	'name',
	'jobPost',
	'email',
	'phone',
	'status',
	'scheduledAt',
	'fit',
	'resume',
	'university',
	'passingYear',
	'linkedin',
	'portfolioUrl',
	'city',
	'appliedAt',
	'appliedFrom',
];

export const formFields = [
	{
		sectionTitle: 'Basic Information',
		fields: ['jobPost', ['name', 'status'], ['email', 'phone'], ['city', 'fit'], 'address'],
	},
	{
		sectionTitle: 'Application Details',
		fields: [['appliedAt', 'appliedFrom'], 'coverLetter', ['resume', 'resumeUrl']],
	},
	{
		sectionTitle: 'Personal Details',
		fields: [
			['educationLevel', 'degree'],
			['school', 'college'],
			['university', 'passingYear'],
			['portfolioUrl', 'linkedin'],
			['github', 'facebook'],
			['website', 'expectedSalary'],
			'skills',
		],
	},

	{
		sectionTitle: 'For Official Use',
		fields: ['notes', 'tags'],
	},
];

export const fields = [
	'jobPost',
	'name',
	'email',
	'phone',
	'address',
	'city',
	'coverLetter',
	'resume',
	'resumeUrl',
	'status',
	'scheduledAt',
	'educationLevel',
	'school',
	'college',
	'degree',
	'university',
	'passingYear',
	'portfolioUrl',
	'linkedin',
	'github',
	'facebook',
	'website',
	'expectedSalary',
	'appliedAt',
	'appliedFrom',
	'experienceLevel',
	'skills',
	'notes',
	'tags',
];
